-- Generated by the database client.
CREATE TABLE branches (
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    branch_id character(26) NOT NULL,
    address text,
    phone_number varchar(50),
    is_home_service boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    open_hour time without time zone,
    close_hour time without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX branches_name_unique ON public.branches USING btree (name);

CREATE UNIQUE INDEX branches_branch_id_unique ON public.branches USING btree (branch_id);